### ISSUE TITLE
Auction House not functioning

### ISSUE THREAD

**Issue by scan16** [StygianTheBest/StygianCore#2]
WorldServer logs indicate the auction house DB table(s) as empty:

_Loading Item Auctions...
>> Loaded 0 auction items. DB table `auctionhouse` or `item_instance` is empty!

Loading Auctions...
>> Loaded 0 auctions. DB table `auctionhouse` is empty._

In reviewing the characters DB, I'm not seeing any tables for items, pricing, history, etc.

**Comment by StygianTheBest** [comment]
The auction house is always empty unless you put something in it. I don't use AH bots in this repack because they slow down the server. I personally use a 3rd party tool that populates the AH with whatever items I want. You can find those tools out there in the mod community.
