### ISSUE TITLE
Missing NPCs in GMisland when using HQ Patches on WOTLK Client

### ISSUE THREAD

**Issue by iceprophecy** [StygianTheBest/StygianCore#35]
Not sure if its a fixable issue, but an FYI for you

please find image https://imgur.com/a/duA2mJT

There would be lower tiered NPC's here normally

**Comment by StygianTheBest** [comment]
That looks like it came from a version of WoW later than 3.3.5a and would explain why you're having issues. I would seek out the 335 patches, or wait until I post mine which work perfectly. Thanks for the report!
