### ISSUE TITLE
Sugestion to help with solo play

### ISSUE THREAD

**Issue by umbraqueen** [StygianTheBest/StygianCore#47]
Would it be possible to make boss affected by crowd control abillity? That way some build would be able to shine in solo play like frost mage.woyld help alot to be able to cc boss that have abillity that cant be stoped but hit like a truck.

**Comment by StygianTheBest** [comment]
Anything is possible if you have the time and resources to research and implement it.  Depending on the boss, there may be better or easier ways to achieve the same goal.

**Comment by umbraqueen** [comment]
I have found a simple way to fix it. Xhanged all the immune mask of the
monster in the game to 0. This way all mob will be affected by cc.
