### ISSUE TITLE
Access Denied for user 'azerothcore'@'localhost'

### ISSUE THREAD

**Issue by veel92** [StygianTheBest/StygianCore#48]
Access Denied for user 'azerothcore'@'localhost'
any idea how to fix this?the doc doesnt say anthing about this

**Comment by StygianTheBest** [comment]
Please be specific when issues. What exactly are you trying to do when this error occurs?

**Comment by veel92** [comment]
happends when i try to [5] Restore Server (StygianCore) and accessing heidiSQL and i couldn't start auth and world either

**Comment by StygianTheBest** [comment]
The system appears to be having an issue communicating with the MySQL database. This shouldn't be happening if your database is running and no configurations were changed. I've had no other reports about this issue, and haven't encountered it myself, so my only guess is it's something to do with your system. I would delete the repack, unzip it again, and follow the directions here:

https://stygianthebest.github.io/projects/server-stygiancore/#getting-started
