### ISSUE TITLE
Questions regarding Solocraft and Random Enchants.

### ISSUE THREAD

**Issue by Palendarel** [StygianTheBest/StygianCore#49]
Hello! Having a real blast with your wonderful repack!  
I am sorry if it's not the good place for this, since what i am here for is not a bug. In some other site you said to come here to ask questions so...
I looked around for answers and dident find any; 
1st - Solocraft. I played with some value in the config files to adjust difficulties in dungeons, since they are way too easy, but haven't accomplish a real difference... 
2nd- Random enchants module... played with config file also...not sure what i was really doing..there is % of chance and... Quality of items?   

For the 2... would you care to explain the settings in those files? Or point me in a direction?
I am really sorry to bother you with this, really.

In all case; thank a lot for this repack!!!! Have a good time!

**Comment by StygianTheBest** [comment]
This is a great place for questions. It's easier for me to collect and address them all properly here. 

- I removed Solocraft a while back, are you running the latest version? VAS Autobalance should be the encounter tuning module for solo play.

- Random Enchants
  - % chance: Each item has a chance to receive up to 3 enchants, so the settings allow you to control the % chance for each possibility. 
  - Quality is minimum and maximum item quality to enchant. The module supports 1(Gray) to 5(Epic). If you want only Blue items enchanted set LowQuality and HighQuality to 4. 
![Item Quality](https://i.imgur.com/Uemt47M.png)

**Comment by Palendarel** [comment]
Ah! You where right about being not on the latest version! 
But now.... the new version don't start when i restore stygian_auth.sql and character from my version to the last one.  All is starting ok before restoring, but not after (in your control tool, after the restore, the world and auth wont start).
One version may not be compatible with the last one?

(Oh! and many thanks for your previous answer!)

**Comment by StygianTheBest** [comment]
The version released today, v2019.03.10, updates all of the new structures to the latest, so yeah, you won't be able to import without making some changes. I suggest installing the latest and re-rolling your toons.
