### ISSUE TITLE
Patching to 2019.03.10 from 2019.03.05

### ISSUE THREAD

**Issue by iceprophecy** [StygianTheBest/StygianCore#51]
Hi Stygian,

Thanks again for continually improving this! We are enjoying it so much!
Going from 03.01 to 03.05 had a patcher.
Will you be making one for this newest version?

Otherwise what would the procedure be to safely move to the newest version while keeping the current accounts and characters in our server?
I unfortunately, broke everything going to 03.01 and we all had to start again :D
Was a good lesson to myself for backing up properly HAHAHAH!

Jay

**Comment by StygianTheBest** [comment]
Glad you're enjoying it! The latest release was not meant to be backward compatible, but if you want to take advantage of new releases and updates you'll have to start using v2019.03.10. 

If you're handy with SQL, you can alter the account/character export files and import them back into the latest version's database. I believe there were only minor changes, but it was such a large refactor process across ALL of the content I don't remember what exactly what was changed. I used a program called WinDiff to verify changes when I worked on the conversions. The bulk of the changes were in the world database.

As an alternative, you could also invoke the GM powers and alter new characters to match the old ones without messing with the database.
