### ISSUE TITLE
I think this is a bug - new here, wanted to help you with your project

### ISSUE THREAD

**Issue by deadlydna2014** [StygianTheBest/StygianCore#54]
I have an issue with npc models appear in random spots also they are not clickable. i have screenshots of these but they are super high resolution. Let me see if i can link or attach them.

https://i.imgur.com/s0QCra3.jpg
the demons or imp stuck in the globe center of screenshot - this is in outlands BC

https://i.imgur.com/FwfTAJM.jpg
infernals in the pillars - icecrown 

https://i.imgur.com/0S8eJde.jpg
infernal at front of boat  north rend area

**Comment by deadlydna2014** [comment]
Also thank you for the repack, i haven't got too far into it but it seems pretty good.

**Comment by zmyzy** [comment]
看不到图片，这是谁发送的邮件？



------------------ 原始邮件 ------------------
发件人: "deadlydna2014"<notifications@github.com>; 
发送时间: 2019年5月9日(星期四) 上午10:06
收件人: "StygianTheBest/StygianCore"<StygianCore@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [StygianTheBest/StygianCore] I think this is a bug - new here, wantedto help you with your project (#54)




我有一个问题，npc模型出现在随机点也不可点击。我有这些截图，但它们是超高分辨率。让我看看我是否可以链接或附加它们。
 
https://i.imgur.com/s0QCra3.jpg
  恶魔或imp卡在全球截屏中心 - 这是在卑鄙的BC省
 
https://i.imgur.com/FwfTAJM.jpg
  支柱中的地狱 - 冰冠冰川
 
https：//i.imgur.com/0S8eJde.jpg
  在船只北面地区前面的地狱
 
- 
您收到此消息是因为您订阅了此主题。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。

**Comment by StygianTheBest** [comment]
The infernals and imps are usually placeholders for scripts and triggers used by the game engine. They should only be visible when GM mode is on, so try turning that off and see if they disappear.
