### ISSUE TITLE
Random Enchants don't work in a group

### ISSUE THREAD

**Issue by Jegethy** [StygianTheBest/StygianCore#56]
I've been playing with a friend and noticed that if an item is rolled, it never gets an enchant. Setting the loot mode to free for all works as usual, but rolling using the default need before greed loot rules means no enchant is ever applied.

**Comment by milestorme** [comment]
Can confirm this

**Comment by StygianTheBest** [comment]
Thanks for the report. It sounds like the author of the module overlooked this, and I never caught it during development of the repack. I bet it's a quick code fix. I'll take a look and resolve it in the next release.

**Comment by StygianTheBest** [comment]
Part of #52
