### ISSUE TITLE
[solved-->Solution attached-->Please add to your FAQ] Can't connect via Hamachi

### ISSUE THREAD

**Issue by da13th** [StygianTheBest/StygianCore#58]
Hi, first I would like to thank you tremendously for your efforts in this repack.

I'm having so much fun with this and it works amazingly well as long as I play alone (with the realmlist set to 127.0.0.1)

I want 1 friend to join the fun, so I installed Hamachi and set the realmlist IP accordingly. 
I also deactivated my firewall and edited the auth database.

The good news: I can connect to the auth server, but not to the world server. It's stuck at this screen (even for me, when I try to access it via the Hamachi IP)

Have you got any suggestions? 

Thank you so much for your help.

![WoWScrnShot_060519_231649](https://user-images.githubusercontent.com/51423202/58991216-06566b00-87e8-11e9-9605-7e70aa52c005.jpg)

![Unbenannt](https://user-images.githubusercontent.com/51423202/58991942-cabca080-87e9-11e9-9ccc-458d79a00c02.png)
![Unbenannt2](https://user-images.githubusercontent.com/51423202/58991944-cabca080-87e9-11e9-8670-f83a61fb67fd.png)

**Comment by da13th** [comment]
I found the solution myself.

@StygianTheBest Please add this Screenshot or something like that to your tutorial page. It will help others tremendously (if they make the same mistake as I did, which is quite likely as the default settings lead you to a different table)

Thank you so much for your amazing repack!
![Unbenannt](https://user-images.githubusercontent.com/51423202/59061496-f13f1200-88a3-11e9-80c8-514138f2e6bb.png)

**Comment by StygianTheBest** [comment]
Thanks for the report. I'll add a section for Hamachi users on my next update.
