### ISSUE TITLE
Random Enchants not working

### ISSUE THREAD

**Issue by Numbo** [StygianTheBest/StygianCore#61]
I just downloaded the latest StygianCore Repack and everything i saw, is working like it should except for Random Enchants. The module is announced on login but not a single item will get a random enchant. Not on Vendor buy, Crafting, Quest reward or looting. everything i tryed wont work. If i modify the .conf.dist or i dont modify it, if i create a .conf (that i have .conf.dist and .conf).. Nothing will Change anything. I cant get it to work. 

If you dont understand something here, just ask me and i will try to write it again, with my girlfriend as translator :D So sry for my bad english, hope you know what i mean.

And i saw that its normal, that a item dont enchant on Vendor buy. Do you think you can add it in the next update ? Would be awesome. If its to much work, i think you dont have to do that^^

**Comment by StygianTheBest** [comment]
Part of #52
