### ISSUE TITLE
[Feature/enhancement] Allow any race-class combination

### ISSUE THREAD

**Issue by NikitaGl** [StygianTheBest/StygianCore#64]
Would be really nice to add an ability to create character of any race with any class. Maybe as module.

**Comment by sh1tdev** [comment]
This is an SQL command and a db edit - and with a bit of searching is readily available.

[http://www.ac-web.org/forums/showthread.php?220281-All-Races-All-Classes-for-Current-Trinity-Build](url)

I assume that doing this will mean you will be missing the classes quests and will need to learn those quest spells another way - could make your own quest or a gm command?

EDIT: There is a possibility you will have skills and all sorts missing - you'd have to manually add them when you spawn in.
