### ISSUE TITLE
error on joining world with patch-z.mpq

### ISSUE THREAD

**Issue by BruceMace** [StygianTheBest/StygianCore#65]
I keep getting this error with patch z, i've tried doing it exactly like the instructions say, drop it in the folder and delete the cache. Thank you

This application has encountered a critical error:

ERROR #132 (0x85100084) Fatal Exception
Program:	C:\Users\Public\Games\World of Warcraft\Wow.exe
Exception:	0xC0000005 (ACCESS_VIOLATION) at 0023:0072DA70

**Comment by BruceMace** [comment]
Oh, also i'm using retail client, with blizz patches up to 3.3.5a

**Comment by jjsr420** [comment]
Same issue. I removed all other (private Server) patches from the data folder, then deleted the cache folder. Still happening. I've tried every fix I can think of. The server i'm trying to start is just for my kids to play on a really fun place that I can develop further. 

Any help would be greatly appreciated.

Removing the Patch-Z.mpq file fixes the errors, but then all the custom items show up with the ? icon.

**Comment by milestorme** [comment]
I had the same issue trying to just use patch.z
The HD client works very well  , i use it , I love it , easy to patch you standard version with https://stygianthebest.github.io/

**Comment by jjsr420** [comment]
404 - Page Not Found

**Comment by jjsr420** [comment]
I found the link. I want to use the normal client though.

**Comment by milestorme** [comment]
I had a friend fix it for me but it has added currency , shouldn’t matter though , try this https://drive.google.com/open?id=1etT8MoA2hzRLNcoryIkDOJSUGVpSg3dW

**Comment by jjsr420** [comment]
OMG you are freaking AWESOME sir!!!! Worked perfectly!

Now, to ready the next generation of WoW players (14, 11, 10, 9)

Thank you so much!

**Comment by jjsr420** [comment]
So, it works. I can get into the game, and run around and everything. Items don't have the ? icon.

Just a warning, though: So far, I haven't been able to get into the Dev/Programmer Isle. It crashes everytime I try to go there. Had to delete a character because when I teleported him there, it crashed, but the char was saved as there, so it just kept crashing.

**Comment by milestorme** [comment]
Yeah it’s possible my guy removed the custom map locals from that patch , probably not ideal for StygianCore since those locations are in the teleport, you can summon a player offline though no need to delete

**Comment by StygianTheBest** [comment]
As stated in the documentation, you should use an unmodified client when applying the HD Client Patch, and you need Patch-Z.mpq if you plan to go to the developer locations.
