### ISSUE TITLE
GM island isn't in teleport list

### ISSUE THREAD

**Issue by BruceMace** [StygianTheBest/StygianCore#67]
gm island isn't in teleport list

**Comment by Whereswaldbkw** [comment]
Did you try ".tele GMIsland"?  Works for me...

**Comment by BruceMace** [comment]
yes, i've tried the .tele command, doesn't work on non gm accounts for me, and programmer isle and designer isle crash the client

**Comment by sh1tdev** [comment]
> 
> 
> yes, i've tried the .tele command, doesn't work on non gm accounts for me, and programmer isle and designer isle crash the client

have you put PATCH-Z in to the wotlk client data folder?

**Comment by StygianTheBest** [comment]
GM Island is most definitely in the list. It sounds like you're missing the required client files as stated in the documentation. Please read over that section carefully.
