### ISSUE TITLE
Fire damage range from fires is bigger than the Object.

### ISSUE THREAD

**Issue by sh1tdev** [StygianTheBest/StygianCore#71]
Fire damage range from fires often larger than the object. You can stand next to some fires and take constant damage from being next to it.

![WoWScrnShot_092619_232812](https://user-images.githubusercontent.com/55241560/65692379-c6c4cf00-e0b5-11e9-87f1-cba203368c3c.jpg)

**Comment by StygianTheBest** [comment]
I reported this issue long ago to the AzerothCore github. It might get fixed.. one day. In the meantime, don't stand so close to the fire. :)
