### ISSUE TITLE
.xp set <rate> invalid syntax.

### ISSUE THREAD

**Issue by HoodOG1** [StygianTheBest/StygianCore#72]
Hey,

i cant change the ".xp rate", since it will lead into a invalid syntax error message. (eg. .xp set 5)
If im using ".xp set rate 5" for example, my rate will get set to 0.

**Comment by Whereswaldbkw** [comment]
the correct format of the command is ".xp set x" where x is the rate you want.  For example, ".xp set 2" will set the rate to 2.  You can also type ".xp view" to view your current rate or ".xp default" to return to the default value.  Max rate and default rate are set in mod_individualxp.conf.dist. If you try to set a rate that is high than the max, you will get an "invalid syntax" error message

**Comment by StygianTheBest** [comment]
You can also set the config variable in mod_individualxp.conf to keep the original unmodified which is the best practice approach.
