### ISSUE TITLE
Dungeon Finder Solo

### ISSUE THREAD

**Issue by LevelChecker** [StygianTheBest/StygianCore#73]
Is there any way within Stygian to queue into a dungeon solo?

**Comment by Whereswaldbkw** [comment]
.tele <dungeon name>

and then walk in 

(that is as long as the account has gm authority)

other than that, no it doesn't have SoloCraft

**Comment by LevelChecker** [comment]
Damn okay

**Comment by StygianTheBest** [comment]
I've never bothered to try and get the Dungeon Finder feature to work since this is designed for solo and small groups.
