### ISSUE TITLE
In Game Calendar does not match up with real life calendar.

### ISSUE THREAD

**Issue by acidmanifesto** [StygianTheBest/StygianCore#77]
Calendar and dates are well ahead of real life calendar which causes issues with ingame events.

**Comment by Whereswaldbkw** [comment]
try looking in mod_customserver.conf.dist for the Timeshift keyword and see what it is set to.  Mine is set to 1.0 and i just logged in and the date was Nov 14.  I would think that the server would get the current date every time you boot it up...

**Comment by StygianTheBest** [comment]
This is likely due to the TimeShift option. You can disable this feature in the config or set it to be 1:1 with the current time.
