### ISSUE TITLE
ERROR!!

### ISSUE THREAD

**Issue by elementalwow** [StygianTheBest/StygianCore#82]
### **I have tried several times to compile this core, but always give the same error. Would you help me?**

![image](https://user-images.githubusercontent.com/57023516/70170976-92205580-16ac-11ea-9380-2963953d07f3.png)
unable to open input file game.lib

**Comment by StygianTheBest** [comment]
StygianCore is a complex project and I do not support compiling the source as it involves a deep understanding of many different things. You should familiarize yourself with compiling the Vanilla Azerothcore builds first, then once you're comfortable with that and adding new modules, come back and try to compile StygianCore.
