### ISSUE TITLE
PVP players drop loot on death not working

### ISSUE THREAD

**Issue by Grimblewald** [StygianTheBest/StygianCore#85]
Under the repack description heading "Life Death Combat" it lists that "PVP kills can allow the player to loot a configurable percentage of the victim’s loot if desired."

This module isn't included in the source modules folder, and doesn't appear to be working in game / is not possible to be enabled.

**Comment by milestorme** [comment]
It’s called money for kills it’s included , just enable it

**Comment by Grimblewald** [comment]
that is covered by a different section 

"A bounty system can award players a configurable amount of money for mob or player kills based on level if desired."

the line "Life Death Combat" it lists that "PVP kills can allow the player to loot a configurable percentage of the victim’s loot if desired." - this implies either gear or bag items.

Sounds to me like the repack includes, or did at some point include [this PvP Script module by talamortis](https://github.com/azerothcore/mod-pvpscript)

**Comment by StygianTheBest** [comment]
> Sounds to me like the repack includes, or did at some point include this PvP Script module by talamortis

No, I wrote this module long before Talamortis created the one that drops a chest. I believe his is based on mine, but I could be mistaken. If so, it should be easy to compile into the core. StygianCore only supports money loot from players.
