### ISSUE TITLE
cmake error 

### ISSUE THREAD

**Issue by vurtne** [StygianTheBest/StygianCore#86]
[ 14%] Building CXX object src/server/game/CMakeFiles/gamePCH.cpp_dephelp.dir/PrecompiledHeaders/gamePCH.cpp.o
In file included from /home/sq/StygianCore/Source/src/server/game/PrecompiledHeaders/gamePCH.cpp:1:
In file included from /home/sq/StygianCore/Source/src/server/game/PrecompiledHeaders/gamePCH.h:7:
In file included from /home/sq/StygianCore/Source/src/server/game/Maps/MapManager.h:14:
In file included from /home/sq/StygianCore/Source/src/server/game/Maps/Map.h:20:
In file included from /home/sq/StygianCore/Source/src/server/game/Grids/GridDefines.h:11:
/home/sq/StygianCore/Source/src/server/game/Grids/NGrid.h:47:58: error: cannot assign to non-static data member within const member function 'SetGridId'
        void SetGridId(const uint32 id) const { i_gridId = id; }
                                                ~~~~~~~~ ^
/home/sq/StygianCore/Source/src/server/game/Grids/NGrid.h:47:14: note: member function 'NGrid::SetGridId' is declared const here
        void SetGridId(const uint32 id) const { i_gridId = id; }
        ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/server/game/CMakeFiles/gamePCH.cpp_dephelp.dir/build.make:63：src/server/game/CMakeFiles/gamePCH.cpp_dephelp.dir/PrecompiledHeaders/gamePCH.cpp.o] error 1
make[1]: *** [CMakeFiles/Makefile2:1415：src/server/game/CMakeFiles/gamePCH.cpp_dephelp.dir/all] error 2
make[1]: *** 正在等待未完成的任务....
[ 14%] Built target revision.h
make: *** [Makefile:130：all] error 2

**Comment by StygianTheBest** [comment]
Never had any issues with CMake, so it's likely that you're not using the specific versions required as noted in the docs.
